# Generated by Django 5.2.4 on 2026-07-10 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0017_employee_chair_rental_fee_employee_contract_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Descrição da Despesa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Despesa')),
                ('is_recurring', models.BooleanField(default=False, help_text='Se marcado, esta despesa será contabilizada no caixa de todos os meses.', verbose_name='Despesa Recorrente Mensal?')),
                ('due_date', models.DateField(help_text='Para recorrentes, usamos apenas o dia. Para únicas, usamos a data exata.', verbose_name='Data de Vencimento/Ocorrência')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='barbershop.unit')),
            ],
        ),
    ]
