# Generated by Django 5.2.4 on 2026-07-29 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_alter_employee_contract_type'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('fixed_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salário Fixo')),
                ('chair_rental_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Aluguel de Cadeira')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_snapshots', to='barbershop.employee')),
            ],
            options={
                'verbose_name': 'Snapshot de Folha',
                'verbose_name_plural': 'Snapshots de Folhas',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
