# Generated by Django 5.2.4 on 2026-08-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payrollsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsnapshot',
            name='contract_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Contrato'),
        ),
    ]
