# Generated by Django 5.2.4 on 2026-07-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_initial'),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cpf',
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='barbershop.unit'),
        ),
    ]
