# Generated by Django 5.2.4 on 2025-10-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0011_alter_unitmedia_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome Base')),
                ('icon', models.CharField(blank=True, choices=[('fa-cut', 'Tesoura'), ('fa-sharp', 'Navalha'), ('fa-comb', 'Pente')], max_length=20, null=True, verbose_name='Ícone')),
            ],
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Duração (em minutos)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barbershop.employee', verbose_name='Funcionário')),
                ('base_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.baseservice', verbose_name='Serviço Base')),
            ],
            options={
                'verbose_name': 'Serviço do Barbeiro',
                'verbose_name_plural': 'Serviços do Barbeiro',
                'ordering': ['name'],
            },
        ),
    ]
