# Generated by Django 5.2.4 on 2026-07-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome Base')),
                ('icon', models.CharField(blank=True, choices=[('fas fa-cut', 'Tesoura / Corte'), ('fas fa-bolt', 'Máquina / Degradê'), ('fas fa-magic', 'Navalha / Acabamento'), ('fas fa-user-tie', 'Barba / Modelagem'), ('fas fa-wind', 'Penteado / Secador'), ('fas fa-tint', 'Lavagem / Hidratação'), ('fas fa-spray-can', 'Química / Pigmentação'), ('fas fa-hand-sparkles', 'Estética / Massagem'), ('fas fa-eye', 'Sobrancelha'), ('fas fa-child', 'Corte Infantil'), ('fas fa-star', 'Pacote Especial')], max_length=50, null=True, verbose_name='Ícone')),
            ],
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Duração (em minutos)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='barbershop.employee', verbose_name='Funcionário')),
                ('base_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.baseservice', verbose_name='Serviço Base')),
            ],
            options={
                'verbose_name': 'Serviço do Barbeiro',
                'verbose_name_plural': 'Serviços do Barbeiro',
                'ordering': ['name'],
            },
        ),
    ]
