# Generated by Django 5.2.4 on 2026-05-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseservice',
            name='icon',
            field=models.CharField(blank=True, choices=[('fas fa-cut', 'Tesoura / Corte'), ('fas fa-bolt', 'Máquina / Degradê'), ('fas fa-magic', 'Navalha / Acabamento'), ('fas fa-user-tie', 'Barba / Modelagem'), ('fas fa-wind', 'Penteado / Secador'), ('fas fa-tint', 'Lavagem / Hidratação'), ('fas fa-spray-can', 'Química / Pigmentação'), ('fas fa-spa', 'Estética / Massagem'), ('fas fa-eye', 'Sobrancelha'), ('fas fa-child', 'Corte Infantil')], max_length=50, null=True, verbose_name='Ícone'),
        ),
    ]
