# Generated by Django 5.2.4 on 2026-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_baseservice_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseservice',
            name='icon',
            field=models.CharField(blank=True, choices=[('fas fa-cut', 'Tesoura / Corte'), ('fas fa-bolt', 'Máquina / Degradê'), ('fas fa-magic', 'Navalha / Acabamento'), ('fas fa-user-tie', 'Barba / Modelagem'), ('fas fa-wind', 'Penteado / Secador'), ('fas fa-tint', 'Lavagem / Hidratação'), ('fas fa-spray-can', 'Química / Pigmentação'), ('fas fa-hand-sparkles', 'Estética / Massagem'), ('fas fa-eye', 'Sobrancelha'), ('fas fa-child', 'Corte Infantil'), ('fas fa-star', 'Pacote Especial')], max_length=50, null=True, verbose_name='Ícone'),
        ),
    ]
