# Generated by Django 5.2.4 on 2025-09-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('dono', 'Dono'), ('cliente', 'Cliente'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], default='cliente', max_length=20),
        ),
    ]
