# Generated by Django 5.2.4 on 2025-07-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_barber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_failed_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionário'), ('dono', 'Dono da Barbearia')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
