# Generated by Django 5.2.4 on 2026-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='barbershop_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('foundation_date', models.DateField(blank=True, null=True)),
                ('max_employees', models.PositiveIntegerField(default=5, verbose_name='Limite de Vagas (Funcionários)')),
                ('max_units', models.PositiveIntegerField(default=1, verbose_name='Limite de Unidades')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Funcionário Ativo')),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_type', models.CharField(choices=[('commission', 'Comissionado (100% Produtividade)'), ('fixed_salary', 'Salário Fixo (+ Comissão)'), ('chair_rental', 'Aluguel de Cadeira (Coworking)')], default='commission', max_length=20)),
                ('fixed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Fixo')),
                ('chair_rental_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aluguel da Cadeira')),
                ('commission_percentage', models.BooleanField(default=False)),
                ('service_commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('can_manage_cashbox', models.BooleanField(default=False)),
                ('can_register_sell', models.BooleanField(default=False)),
                ('can_create_appointments', models.BooleanField(default=False)),
                ('system_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Dom'), (1, 'Seg'), (2, 'Ter'), (3, 'Qua'), (4, 'Qui'), (5, 'Sex'), (6, 'Sab')])),
                ('start_morning_work', models.TimeField(blank=True, default='07:00', null=True)),
                ('end_morning_work', models.TimeField(blank=True, default='12:00', null=True)),
                ('start_afternoon_work', models.TimeField(blank=True, default='12:30', null=True)),
                ('end_afternoon_work', models.TimeField(blank=True, default='23:00', null=True)),
                ('morning_available', models.BooleanField(blank=True, default=False, null=True)),
                ('afternoon_available', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(choices=[('barbeiro', 'Barbeiro'), ('gerente', 'Gerente'), ('caixa', 'Caixa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('cep_address', models.CharField(max_length=9)),
                ('street_address', models.CharField(max_length=255)),
                ('number_address', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about_units/')),
                ('map_link', models.TextField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('banner', 'Banner'), ('hairstyle', 'Foto de Corte de Cabelo'), ('shop_photo', 'Foto da Barbearia'), ('product', 'Foto de Produto')], max_length=12)),
                ('image', models.ImageField(upload_to='unit_media/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
