# Generated by Django 5.2.4 on 2025-08-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
