# Generated by Django 5.2.4 on 2026-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('commission', 'Comissionado (100% Produtividade)'), ('fixed_salary', 'Salário Fixo (+ Comissão)'), ('fixed_only', 'Apenas Salário Fixo'), ('chair_rental', 'Aluguel de Cadeira (Coworking)')], default='commission', max_length=20),
        ),
    ]
