# Generated by Django 5.2.4 on 2025-08-26 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_barbershop_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.BooleanField(default=False)),
                ('service_commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('can_manage_cashbox', models.BooleanField(default=False)),
                ('can_register_sell', models.BooleanField(default=False)),
                ('can_create_appointments', models.BooleanField(default=False)),
                ('system_access', models.BooleanField(default=False)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='barbershop.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
