# Generated by Django 5.2.4 on 2025-09-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
