# Generated by Django 5.2.4 on 2025-09-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_barbershop_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='barbershop.employee')),
            ],
            options={
                'verbose_name': 'Ausência de Funcionário',
                'verbose_name_plural': 'Ausências de Funcionários',
            },
        ),
        migrations.CreateModel(
            name='UnitMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('banner', 'Banner'), ('photo', 'Foto')], max_length=10)),
                ('image', models.ImageField(upload_to='unit_media/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='barbershop.unit')),
            ],
            options={
                'verbose_name': 'Mídia da Unidade',
                'verbose_name_plural': 'Mídias da Unidade',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('start_morning_work', models.TimeField(default='07:00')),
                ('end_morning_work', models.TimeField(default='12:00')),
                ('start_afternoon_work', models.TimeField(default='12:01')),
                ('end_afternoon_work', models.TimeField(default='17:00')),
                ('morning_available', models.BooleanField(default=False)),
                ('afternoon_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='barbershop.employee')),
            ],
            options={
                'verbose_name': 'Dia de Trabalho do Funcionário',
                'verbose_name_plural': 'Dias de Trabalho dos Funcionários',
                'unique_together': {('employee', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(choices=[('barbeiro', 'Barbeiro'), ('gerente', 'Gerente'), ('caixa', 'Caixa')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='barbershop.employee')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'unique_together': {('employee', 'occupation')},
            },
        ),
        migrations.CreateModel(
            name='UnitHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='barbershop.unit')),
            ],
            options={
                'verbose_name': 'Feriado da Unidade',
                'verbose_name_plural': 'Feriados da Unidade',
                'unique_together': {('unit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UnitWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='barbershop.unit')),
            ],
            options={
                'verbose_name': 'Dia de Trabalho da Unidade',
                'verbose_name_plural': 'Dias de Trabalho da Unidade',
                'unique_together': {('unit', 'weekday')},
            },
        ),
    ]
