# Generated by Django 5.2.4 on 2025-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_employeeabsence_unitmedia_employeeworkday_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeabsence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeeworkday',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitholiday',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitmedia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitworkday',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='employeeworkday',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unitholiday',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unitworkday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeworkday',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Dom'), (1, 'Seg'), (2, 'Ter'), (3, 'Qua'), (4, 'Qui'), (5, 'Sex'), (6, 'Sab')]),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('barbershop', 'name'), name='unique_unit_name_per_barbershop'),
        ),
    ]
