# Generated by Django 5.2.4 on 2025-09-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0006_alter_employeeabsence_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkday',
            name='afternoon_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeeworkday',
            name='end_afternoon_work',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='employeeworkday',
            name='end_morning_work',
            field=models.TimeField(blank=True, default='12:00', null=True),
        ),
        migrations.AlterField(
            model_name='employeeworkday',
            name='morning_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeeworkday',
            name='start_afternoon_work',
            field=models.TimeField(blank=True, default='12:01', null=True),
        ),
        migrations.AlterField(
            model_name='employeeworkday',
            name='start_morning_work',
            field=models.TimeField(blank=True, default='07:00', null=True),
        ),
    ]
