# Generated by Django 5.2.4 on 2025-09-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0007_alter_employeeworkday_afternoon_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkday',
            name='end_afternoon_work',
            field=models.TimeField(blank=True, default='23:00', null=True),
        ),
        migrations.AlterField(
            model_name='employeeworkday',
            name='start_afternoon_work',
            field=models.TimeField(blank=True, default='12:30', null=True),
        ),
    ]
