# Generated by Django 5.2.4 on 2025-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0009_unit_city_unit_instagram_link_unit_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='foundation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
