# Generated by Django 5.2.4 on 2025-09-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0010_barbershop_foundation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmedia',
            name='media_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('hairstyle', 'Foto de Corte de Cabelo'), ('shop_photo', 'Foto da Barbearia'), ('product', 'Foto de Produto')], max_length=12),
        ),
    ]
