# Generated by Django 5.2.4 on 2026-02-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0011_alter_unitmedia_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='map_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
