# Generated by Django 5.2.4 on 2026-02-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0012_unit_map_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbershop',
            old_name='about',
            new_name='description',
        ),
        migrations.AddField(
            model_name='unit',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_units/'),
        ),
        migrations.AddField(
            model_name='unit',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
