# Generated by Django 5.2.4 on 2026-02-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0013_rename_about_barbershop_description_unit_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
