# Generated by Django 5.2.4 on 2026-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0014_employee_bio_employee_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='max_employees',
            field=models.PositiveIntegerField(default=5, verbose_name='Limite de Vagas (Funcionários)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Funcionário Ativo'),
        ),
    ]
