# Generated by Django 5.2.4 on 2026-05-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0015_barbershop_max_employees_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='max_units',
            field=models.PositiveIntegerField(default=1, verbose_name='Limite de Unidades'),
        ),
    ]
