# Generated by Django 5.2.4 on 2026-07-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0016_barbershop_max_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='chair_rental_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aluguel da Cadeira'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('commission', 'Comissionado (100% Produtividade)'), ('fixed_salary', 'Salário Fixo (+ Comissão)'), ('chair_rental', 'Aluguel de Cadeira (Coworking)')], default='commission', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Fixo'),
        ),
    ]
