# Generated by Django 5.2.4 on 2026-07-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_appointment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='barber_commission_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
